### ISSUE TITLE
ERROR: syntax: "module" expression not at top level

### ISSUE THREAD

**Issue by JinyanTeng** [stevengj/ChangePrecision.jl#10]
When I run this code
```jl
@changeprecision Float32 include("xxx")
```
the error message
```
ERROR: syntax: "module" expression not at top level
```
was observed. How can I fix it ? Thanks.

**Comment by stevengj** [comment]
Right now the [`include` implementation in ChangePrecision](https://github.com/stevengj/ChangePrecision.jl/blob/fae7998d9a24b47bc51e4807f60a44e656d867fa/src/ChangePrecision.jl#L103-L111) is too simplistic — it wraps everything in a `begin...end` block, which doesn't work for top-level statements like module definitions.

The right thing is a more sophisticated version like the [`include` implementation in SoftScope.jl](https://github.com/stevengj/SoftGlobalScope.jl/blob/master/src/SoftGlobalScope.jl#L202-L224), which we could port/adapt to this module.

(That being said, if you are using ChangePrecision.jl in "serious" code projects that have modules etcetera, you should probably re-think your design.  ChangePrecision is a quick hack that is useful for experiments, but for long-term maintenance you should really write precision-independent code.)

**Comment by JinyanTeng** [comment]
Thank you very much.

**Comment by stevengj** [comment]
Probably we should just use the `include(mapexpr, ....)` function provided by Julia 1.5
