### ISSUE TITLE
Meta.parse slower than conversion

### ISSUE THREAD

**Issue by simonbyrne** [stevengj/ChangePrecision.jl#14]
If using a generic type `FT`, a literal `7.3` will convert to `Main.parse(FT, "7.3")`, which is much slower than using `FT(7.3)` (and also won't work on a GPU).

```
julia> using ChangePrecision, BenchmarkTools

julia> f(x::FT) where {FT} = @changeprecision FT x + 7.3
f (generic function with 1 method)

julia> g(x::FT) where {FT} = x + FT(7.3)
g (generic function with 1 method)

julia> @btime f(1f0)
  36.380 ns (0 allocations: 0 bytes)
8.3f0

julia> @btime g(1f0)
  1.083 ns (0 allocations: 0 bytes)
8.3f0
```

**Comment by stevengj** [comment]
It may be slower, but it's much more likely to be what the user wants.

For example, if you are changing to `BigFloat`, you will get `parse(BigFloat, "7.3")`, which uses the full precision and is completely different from `BigFloat(7.3)`.

**Comment by stevengj** [comment]
See also my explanation here: https://discourse.julialang.org/t/ann-changeprecision-jl/6721/10?u=stevengj 

also here: https://discourse.julialang.org/t/bigfloat-promotion-rules-and-constants-in-functions/14573/7?u=stevengj

**Comment by stevengj** [comment]
I guess you know that already, but my main point is:

* The use of `parse` here is intentional, and is crucial to obtain the desired behavior.
* Performance is less of a concern — ChangePrecision.jl is meant for quick hacks, not for production code.
