### ISSUE TITLE
Irrationals

### ISSUE THREAD

**Issue by antoine-levitt** [stevengj/ChangePrecision.jl#2]
`pi+2` will get parsed into a Float64, and so will `sin(pi/4)`. It seems doing this properly would be hard, so a simple solution is to just convert all irrationals to floats at parse time.

I tried playing around to add it, but I don't quite get the way changeprecision works in your framework.

**Comment by stevengj** [comment]
See also JuliaLang/julia#24245, which would make this quite a bit easier.

In practice, if we just convert Irrational in the `intfuncs` and also for integer or rational combined with an irrational in one of the common binary functions, I think that will cover pretty much all common use cases while retaining precision in cases where it is explicitly requested.
