### ISSUE TITLE
help porting the technique

### ISSUE THREAD

**Issue by JeffreySarnoff** [stevengj/ChangePrecision.jl#4]
Users have requested that I provide a similar modality to engage [the safer Int types](https://github.com/JeffreySarnoff/SaferIntegers.jl).  Ideally,
```
@safer_integers begin
    # code
end

@safer_integers begin
    include("my_toplevel_sourcefile")
end
```
and each occurance of Int, UInt, Int8,..,Int128, UInt8,..,UInt128 is replaced (prepending "Safe").

I have looked at your code; the emphasis on float functions is obscuring the wrap and swap mechanism somewhat.  Any direction or helpful hints?

**Comment by stevengj** [comment]
Replacing explicit declarations of `Int` etc. with `SafeInt` is quite different from what ChangePrecision does.  If you explicitly say `Float64`, it won't be affected by ChangePrecision — the `@changeprecision` macro only affects case where a `Float64` would have been created by default.

If you just want to search and replace literal integers and replace them with `Safe(n)` calls, and replace explicit `Int` declarations with `SafeInt`, that is a much easier task: just walk the expression tree and do the replacements.

**Comment by JeffreySarnoff** [comment]
what is the easiest pkg or macro set to apply and get walk the tree and replace these?

**Comment by stevengj** [comment]
Well, there is https://github.com/MikeInnes/MacroTools.jl.   It's pretty easy to write an expression-tree walker, though.  Something like:

```jl
safeexpr(x) = x
safeexpr(n::Integer) = :(SafeInteger($n))
const SafeT = Dict(:Int => :SafeInt, :Int32 => :SafeInt32)
safeexpr(s::Symbol) = get(SafeT, s, s)
safeexpr(e::Expr) = Expr(e.head, safeexpr.(e.args)...)
macro safeinteger(expr)
    esc(safeexpr(expr))
end
```
should be enough, assuming you've defined a polymorphic `SafeInteger(n)` function that produces a wrapper of the appropriate type.
