### ISSUE TITLE
ChangePrecision breaks inference

### ISSUE THREAD

**Issue by antoine-levitt** [stevengj/ChangePrecision.jl#6]
Using ChangePrecision gives a large slowdown on a sample code. I think this is because of inference issues. MWE:
```julia
@changeprecision Float64 begin
    function heat(D,Nx)
        T = typeof(D)
        u = zeros(T,Nx)
    end

    Nx = 10
    D = 1.14

    @code_warntype heat(D,Nx)
end
```
This is on 0.6. Changing zeros(T,Nx) to zeros(Nx) works fine.

**Comment by stevengj** [comment]
It looks like this may be a problem with inference in Julia 0.6.  In Julia 0.7 it works fine.

**Comment by antoine-levitt** [comment]
That's right! Closing.
