### ISSUE TITLE
Bad interaction with `@.` macro

### ISSUE THREAD

**Issue by antoine-levitt** [stevengj/ChangePrecision.jl#9]
`@changeprecision Float64 @. 3 + [1. 2.]` gives `ERROR: MethodError: no method matching +(::Int64, ::Array{Float64,2})`

**Comment by stevengj** [comment]
Whoops, it looks like it deletes the `@.` call … seems like that should be easy to fix.
```jl
julia> macroexpand(Main, :(@changeprecision Float64 @. 3 + [1. 2.]))
:((ChangePrecision.+)(Float64, 3, [1.0 2.0]))
```
